@extends('welcome')
@section('header')
    @include('home/global/header')
@endsection
@section('main')
    @include('home/views/allLinks')
@endsection
@section('footer')
    @include('home/global/footer')
@endsection
